/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Pinger_constants.h"

namespace facebook { namespace netnorad { namespace thrift {

const PingerConstants g_Pinger_constants;

PingerConstants::PingerConstants() {
}

}}} // namespace

