/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Pinger_CONSTANTS_H
#define Pinger_CONSTANTS_H

#include "Pinger_types.h"

namespace facebook { namespace netnorad { namespace thrift {

class PingerConstants {
 public:
  PingerConstants();

};

extern const PingerConstants g_Pinger_constants;

}}} // namespace

#endif
